### ISSUE TITLE
List iterator crashes if List was improperly constructed

### ISSUE THREAD

**Issue by serjek** [haxetink/tink_pure#11]
Let's say we have incoming data where we expect List and that is parsed like this:
```js
function transform(data:Test) {
	trace(data);
	trace(data.l);
	trace(data.l.iterator());
	for (m in data.l) trace(m);
}
var incoming = haxe.Json.parse('{"l":""}');
transform(incoming);

...
typedef Test = {
	var l(default, never):tink.pure.List<String>;
}
```
Following will output:
`src/MainClient.hx:7: { l: '' }`
`src/MainClient.hx:8: `
`src/MainClient.hx:9: { list: [ '' ] }`
and then crash:
`TypeError: Cannot read property 'length' of undefined
    at tink_pure_NodeIterator.next`

**Comment by back2dos** [comment]
There's nothing we can do here, because the code is totally subverting the type system. It's not even specific to tink_pure: [using a plain `Iterable`, it will crash the same way](https://try.haxe.org/#16E32).

You could always use tink_json ;)
