### ISSUE TITLE
Some basic info about the project

### ISSUE THREAD

**Issue by xm75** [haxetink/tink_pure#15]
Is tink_pure ready to be used in real projects (if it is, you may want to fix the 404 link on https://lib.haxe.org/p/tink_pure/)?
Also, I'm interested in how it compares with things like immutable.js or clojure's persistent data structures.

It may be useful to document some of this things in a README file.

**Comment by back2dos** [comment]
Well, tink_pure is used in real project, so I guess you can say it's "ready". That said, it compares poorly to immutable.js or clojure. It's not horrible, but the implementation is naive and therefore probably quite slow (I haven't actually benchmarked anything, but seems like a relatively safe assumption) and should definitely be replaced at some point. In practice, it proved good enough for frontend development. Unless you're using coconut, you'll probably be better off using a native lib optimized for its runtime ;)

**Comment by xm75** [comment]
I'm looking for something cross-platform, so I don't have a such luxury :)
If you guys plan to replace this naive implementation with something more serious, I think this lib will be very useful - AFAIK there's no other cross-platform way to get persistent data structures in Haxe. Also, some platforms don't really have good native libs for this things.

I'm most interested in persistent maps/records at this point. There is an open issue "Mapping leaks memory" - I guess that will also wait for a new implementation?
